### ISSUE TITLE
.NET 7

### ISSUE THREAD

**Issue by BenjaminAbt** [mycsharp/HttpUserAgentParser#35]
- [ ] Move to .NET 7
- [ ] Evaluate Regex Source Code Generators

**Comment by gfoidl** [comment]
> Evaluate Regex Source Code Generators

Right now there are targets for NS2.0, NS2.1 and .NET 6. Do you want to drop these and just rely on .NET 7?
.NET 6 as LTS should be kept at least. As the regex SG is only available from .NET 7 onwards this has to be considered. Should be quite simple though, with pre .NET 7 having the Regex as field returned by a method, just the same way as the SG-one does, so that usages can be the same for all targets.

**Comment by BenjaminAbt** [comment]
Oh, I thought the targets for 7 are also there now.
